# Generated by Django 4.2.6 on 2023-10-11 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrera',
            new_name='Departamento',
        ),
    ]
