# Generated by Django 4.2.6 on 2023-10-14 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_carrera_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.publicacion')),
            ],
        ),
    ]
