# Generated by Django 4.2.6 on 2023-10-14 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_comentario'),
    ]

    operations = [
    ]
