# Generated by Django 4.2.6 on 2023-10-14 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20231014_1852'),
    ]

    operations = [
    ]
