# Generated by Django 4.2.6 on 2023-10-15 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_usuario_contraseña_usuario_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='gmail',
            new_name='email',
        ),
    ]
