# Generated by Django 4.2.6 on 2023-10-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_rename_gmail_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='re_password',
            field=models.CharField(max_length=128),
            preserve_default=False,
        ),
    ]
