# Generated by Django 4.2.6 on 2023-10-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_usuario_re_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='re_password',
        ),
    ]
